"$schema" = "http://json-schema.org/draft-07/schema#"

title = "Todo (TOML)"
description = "a TOML demo of urljsf"

[properties.name]
type = "string"
description = "**What** is _this_ list about?"

[properties.tasks]
type = "array"
description = "What are the things that need to get done?"

[properties.tasks.items]
"$ref" = "#/definitions/Task"

[definitions.Task]
type = "object"

[definitions.Task.properties.complete]
type = "boolean"
description = "Is it done?"
default = false

[definitions.Task.properties.task]
type = "string"
description = "**What** needs to be done?"

[definitions.Task.properties.deadline]
type = "string"
description = "**When** does it need to be done?"
format = "date-time"
