"$schema" = "https://pixi.sh/v0.31.0/schema/manifest/schema.json"

[project]
name = "urljsf"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks] # aliases ##############################################################

# TODO: "check" should do more validation and reporting
dev = {depends-on = ["fix", "lint", "build", "dist", "test", "docs"]}
fix = {depends-on = [
  "fix-toml-taplo",
  "fix-js-dedupe",
  "fix-js-markdownlint",
  "fix-js-prettier",
  "fix-py-ruff",
]}
lint = {depends-on = [
  "lint-actionlint",
  "lint-py-ruff",
  "lint-js-prettier",
  "lint-js-markdownlint",
  "lint-py-mypy",
]}
build = {depends-on = [
  "build-schema",
  "build-js-lib",
  "build-js-app",
  "build-py-static",
]}
build-schema = {depends-on = [
  "build-schema-props",
  "build-schema-json",
  "build-schema-py",
  "build-schema-ts",
]}
dist = {depends-on = ["dist-npm", "dist-pypi", "dist-hash"]}
test = {depends-on = ["test-pytest", "test-oldest-pytest", "test-report"]}
docs = {depends-on = ["docs-sphinx"]}

# fragments ####################################################################
[tasks.prettier--]
cmd = """
yarn prettier
  --list-different
  --cache
  --cache-location build/.cache/prettier
  "*.{yml,json,md}"
  "{docs,tests,src,js,.github}/**/*.{md,json,yml,yaml,css,ts,tsx,ts,mjs}"
"""
[tasks.markdownlint--]
cmd = """
yarn markdownlint-cli2 "*.md" "{docs,tests,src,js,.github}/**/*.{md}"
"""
[tasks.py-static--]
description = "TODO: should be rolled into webpack build/watch"
cmd = """
rm -rf src/urljsf/_static/
&& cp -r js/dist/urljsf src/urljsf/_static/urljsf
&& rm -rf src/urljsf/_static/urljsf/demo/
"""
[tasks.platform--]
cmd = '''
mkdir -p build
&& python -c '
import platform; u = platform.uname(); print(f"{u.system}-{u.machine}".lower())
' > build/platform.txt
'''
[tasks.pip-e--]
cmd = """
python -m pip install
  -vv
  -e .
  --no-deps
  --no-build-isolation
  --disable-pip-version-check
  --ignore-installed
"""

[tasks.schema-vars--]
cmd = '''echo
  PROPS_TS=js/src/_props.ts
  PROPS_JSON=docs/_static/schema/v0/props.schema.json
  SCHEMA_TOML=$PIXI_PROJECT_ROOT/docs/_static/schema/form.schema.toml
  SCHEMA_JSON=$PIXI_PROJECT_ROOT/docs/_static/schema/v0/form.schema.json
  SCHEMA_TS=$PIXI_PROJECT_ROOT/js/src/_schema.ts
  SCHEMA_PY=$PIXI_PROJECT_ROOT/src/urljsf/_schema/__init__.py'''

[tasks.schema-ts-json--]
cmd = """python scripts/schema.py $PROPS_TS $PROPS_JSON"""

[tasks.schema-toml-json--]
cmd = """python scripts/schema.py $SCHEMA_TOML $SCHEMA_JSON"""

[feature.tasks-build.tasks.schema-json-ts--]
cmd = """python scripts/schema.py $SCHEMA_JSON $SCHEMA_TS"""

[feature.tasks-build.tasks.schema-json-py--]
cmd = """python scripts/schema.py $SCHEMA_JSON $SCHEMA_PY"""


[feature.tasks-build.tasks.schema-all--]
cmd = """
pixi r build-schema-props
&& pixi r schema-toml-json--
&& pixi r schema-json-ts--
"""

# setup ########################################################################
[feature.tasks-build.tasks.setup-js]
cmd = "yarn"
inputs = ["{yarn.lock,package.json,.yarnrc.yml}", "js/package.json"]
outputs = ["node_modules/.yarn-state.yml"]

[feature.tasks-lint.tasks.setup-pip-lint]
cmd = """pixi r -e lint pip-e--"""
inputs = ["pyproject.toml"]

[feature.tasks-dev.tasks.setup-pip-test]
cmd = """pixi r -e test pip-e--"""
inputs = ["pyproject.toml"]

[feature.tasks-test-oldest.tasks.setup-pip-test-oldest]
cmd = """pixi r -e test-oldest pip-e--"""
inputs = ["pyproject.toml"]

[feature.tasks-dev.tasks.setup-pip-dev]
cmd = """pixi r -e dev pip-e--"""
inputs = ["pyproject.toml"]

[feature.tasks-docs.tasks.setup-pip-docs]
cmd = """pixi r -e docs pip-e--"""
inputs = ["pyproject.toml"]

# build ########################################################################
[feature.tasks-build.tasks.build-js-lib]
cmd = "yarn build:lib"
depends-on = ["setup-js", "build-schema-ts"]
inputs = ["node_modules/.yarn-state.yml", "js/src", "js/{package,tsconfig}.json"]
outputs = ["js/lib"]

[feature.tasks-build.tasks.build-js-app]
cmd = "yarn build:app"
depends-on = ["build-js-lib"]
inputs = ["node_modules/.yarn-state.yml", "js/lib", "js/webpack.config.mjs"]
outputs = ["js/dist"]

[feature.tasks-build.tasks.build-py-static]
cmd = """pixi r py-static--"""
depends-on = ["build-js-app"]
inputs = ["js/dist"]
outputs = ["src/urljsf/_static", "!**/demo/"]

[feature.tasks-build.tasks.dist-npm]
cmd = "mkdir -p dist && cd dist && npm pack ../js"
depends-on = ["build-js-app"]
inputs = ["node_modules/.yarn-state.yml", "js/{dist,LICENSE,README.md,package.json}"]
outputs = ["dist/*.tgz"]

[feature.tasks-build.tasks.dist-pypi]
cmd = "pyproject-build . --no-isolation"
depends-on = ["build-py-static", "build-schema-py"]
inputs = ["{pyproject.toml,LICENSE,README.md}", "src"]
outputs = ["dist/*.whl", "dist/*.tar.gz"]

[feature.tasks-build.tasks.dist-hash]
cmd = """
rm -rf dist/SHA256SUMS
&& python -c 'from hashlib import sha256; from pathlib import Path; [
  print(f"{sha256(p.read_bytes()).hexdigest()}  {p.name}")
  for p in sorted(Path("dist").glob("*"))
  if p.name != "SHA256SUMS"
]'
> dist/SHA256SUMS
&& cat dist/SHA256SUMS
&& ls -hs dist
"""
depends-on = ["dist-pypi", "dist-npm"]
inputs = ["dist", "!dist/SHA256SUMS"]
outputs = ["dist/SHA256SUMS"]

[feature.tasks-build.tasks.build-schema-props]
cmd = """export $(pixi r schema-vars--) && pixi r schema-ts-json--"""
inputs = ["js/src/_props.ts", "scripts/schema.py"]
outputs = ["docs/_static/schema/v0/props.schema.json"]

[feature.tasks-build.tasks.build-schema-json]
cmd = """export $(pixi r schema-vars--) && pixi r schema-toml-json--"""
inputs = ["docs/_static/schema/form.schema.toml", "scripts/schema.py"]
outputs = ["docs/_static/schema/v0/form.schema.json"]

[feature.tasks-build.tasks.build-schema-ts]
cmd = """export $(pixi r schema-vars--) && pixi r schema-json-ts--"""
inputs = ["docs/_static/schema/v0/form.schema.json", "scripts/schema.py"]
outputs = ["js/src/_schema.ts"]
depends-on = ["build-schema-json"]

[feature.tasks-build.tasks.build-schema-py]
cmd = """export $(pixi r schema-vars--) && pixi r schema-json-py--"""
inputs = ["docs/_static/schema/v0", "scripts/schema.py"]
outputs = ["src/urljsf/_schema"]
depends-on = ["build-schema-json"]

# fix ##########################################################################
[feature.tasks-lint.tasks.fix-toml-taplo]
cmd = """
  taplo fmt
    --option=array_auto_collapse=false
    --option=array_auto_expand=true
    --option=compact_inline_tables=true
    --option=column_width=88
    --option=indent_string="  "
    *.toml
    docs/**/*.toml
    """
inputs = ["*.toml", "docs/**/*.toml"]

[feature.tasks-lint.tasks.fix-js-prettier]
cmd = "pixi r prettier-- --write"
depends-on = ["setup-js"]
inputs = [
  "*.{yml,json,md}",
  "{docs,tests,src,js,.github}/**/*.{md,json,yml,yaml,css,ts,tsx,ts,mjs}",
  "!src/**/_static",
]
[feature.tasks-lint.tasks.fix-js-markdownlint]
cmd = "pixi r markdownlint-- --fix"
depends-on = ["setup-js"]
inputs = ["*.{md,json}", "{docs,tests,src,js,.github}/**/*.{md}", "!src/**/_static"]

[feature.tasks-lint.tasks.fix-js-dedupe]
cmd = "yarn yarn-berry-deduplicate --fail --strategy fewer"
depends-on = ["setup-js"]
inputs = ["node_modules/.yarn-state.yml", "package.json"]
outputs = ["yarn.lock"]

[feature.tasks-lint.tasks.fix-py-ruff]
cmd = "ruff format && ruff check --fix-only"
inputs = ["pyproject.toml", "{src,tests,docs,scripts}/**/*.py"]

# lint #########################################################################
[feature.tasks-lint.tasks.lint-actionlint]
cmd = "actionlint -shellcheck=shellcheck -pyflakes=pyflakes"
inputs = [".github/workflows"]

[feature.tasks-lint.tasks.lint-py-ruff]
cmd = "ruff format --check && ruff check"
inputs = ["pyproject.toml", "{src,tests,docs,scripts}/**/*.py"]

[feature.tasks-lint.tasks.lint-py-mypy]
cmd = "mypy -p urljsf"
inputs = ["pyproject.toml", "{src,tests}/**/*.py"]
depends-on = ["setup-pip-lint"]

[feature.tasks-lint.tasks.lint-js-prettier]
cmd = "pixi r prettier--"
depends-on = ["setup-js"]
inputs = [
  "*.{yml,json,md}",
  "{docs,tests,src,js,.github}/**/*.{md,json,yml,yaml,css,ts,tsx,ts,mjs}",
  "!src/**/_static",
]

[feature.tasks-lint.tasks.lint-js-markdownlint]
cmd = "pixi r markdownlint--"
depends-on = ["setup-js"]
inputs = ["*.{md,json}", "{docs,tests,src,js,.github}/**/*.{md}", "!src/**/_static"]

# test #########################################################################
[feature.tasks-test.tasks.test-pytest]
cmd = """
export PIXI_PLATFORM=$(cat build/platform.txt)
&& export COVERAGE_FILE=build/reports/test_pytest_$PIXI_PLATFORM.coverage
&& pytest
  -n auto
  --html=build/reports/test_pytest_$PIXI_PLATFORM.html
  --self-contained-html
  --cov-report=html:build/reports/test_pytest_htmlcov-$PIXI_PLATFORM/
  --cov-report=term-missing:skip-covered
  --cov=urljsf
  --cov-branch
  --cov-context=test
  --no-cov-on-fail
  --cov-fail-under=100
"""
depends-on = ["setup-pip-test", "build-py-static", "platform--"]
inputs = ["{tests,src/urljsf}/**/*.{py,rst,json}", "src/urljsf/{_static,_templates}"]
outputs = ["build/reports/test_*"]

[feature.tasks-test.tasks.test-report]
cmd = '''
python -c 'from pathlib import Path;
print("""
  <html>
  <style>
    html {font-family: sans-serif;}
    iframe {position: absolute; top: 0; height: 99vh; width: 79vw; right: 0;}
    ul {display: block; max-width: 19vw;}
  </style>
  <body>
    <ul>""");
ps = [
  (
    f"""./{p.name}{"/index.html" if p.is_dir() else ""}""",
    " ".join(p.stem.split("_", 2))
  )
  for p in sorted(Path("build/reports/").iterdir())
  if p.is_dir() or p.name.endswith(".html") and p.name != "index.html"
];
[print(f"""
      <li><a href="{u}" target="main">{n}</a></li>""") for u, n in ps];
print(f"""
    </ul>
    <iframe name="main" src="{ps[0][0]}"></iframe>
  </body>
</html>""")
' > build/reports/index.html
'''

# test-oldest ##################################################################
[feature.tasks-test-oldest.tasks.test-oldest-pytest]
cmd = """
export PIXI_PLATFORM=$(cat build/platform.txt)
&& pytest
  -n auto
  --html=build/reports/test-oldest_pytest_$PIXI_PLATFORM.html
  --self-contained-html
"""
depends-on = ["setup-pip-test-oldest", "build-py-static", "platform--"]
inputs = ["{tests,src/urljsf}/**/*.{py,rst,json}", "src/urljsf/{_static,_templates}"]
outputs = ["build/reports/test-oldest_*"]

# docs #########################################################################
[feature.tasks-docs.tasks.docs-scour]
cmd = """
export SCOUR_ARGS="scour --enable-id-stripping --enable-comment-stripping"
&& cd docs/_static
&& $SCOUR_ARGS logo-inkscape.svg logo.svg
&& $SCOUR_ARGS icon-inkscape.svg icon.svg
"""
inputs = ["docs/_static/*-inkscape.svg"]
outputs = ["docs/_static/*.svg", "!*inkscape.svg"]

[feature.tasks-docs.tasks.docs-sphinx]
inputs = [
  "*.md",
  "*.toml",
  "src/**/*.py",
  "dist/*.whl",
  "docs/**/*.{css,ipynb,md,py}",
  "!**/.ipynb_checkpoints",
]
depends-on = ["setup-pip-docs", "docs-scour"]
outputs = ["build/docs"]
cmd = """
  export PYDEVD_DISABLE_FILE_VALIDATION=1
  && sphinx-build -W --keep-going --color -b html docs build/docs
"""

# watch ########################################################################
[feature.tasks-build.tasks.watch-js-lib]
cmd = "yarn build:lib --watch"
depends-on = ["setup-js"]

[feature.tasks-build.tasks.watch-js-app]
cmd = "yarn build:app --watch"
depends-on = ["setup-js"]

[feature.tasks-build.tasks.watch-py-static]
cmd = """
watchfiles "pixi r py-static--" js/dist
"""

[feature.tasks-build.tasks.watch-schema]
cmd = """
export $(pixi r schema-vars--)
&& watchfiles "pixi r schema-all--" $SCHEMA_TOML $PROPS_TS
"""

[feature.tasks-docs.tasks.watch-docs]
depends-on = ["setup-pip-docs"]
cmd = """
rm -rf build/watch-docs
&& sphinx-autobuild docs build/watch-docs
  --write-all
  --jobs 8
  --color
  --watch src
"""

# envs #########################################################################
[environments]
build = ["deps-build", "tasks-build", "deps-pip"]
test = ["deps-test", "deps-run", "deps-pip", "tasks-test"]
test-oldest = [
  "deps-pip",
  "deps-test",
  "deps-run",
  "deps-run-oldest",
  "tasks-test-oldest",
]
lint = ["deps-pip", "deps-build", "deps-lint", "deps-run", "tasks-lint"]
docs = ["deps-pip", "deps-docs", "deps-run", "deps-build", "tasks-docs"]
dev = ["deps-pip", "deps-build", "deps-test", "deps-docs", "deps-lint", "tasks-dev"]

# deps #########################################################################
[feature.deps-pip.dependencies]
pip = "*"
flit = ">=3.9.0,<4.0.0a0"

[feature.deps-run.dependencies]
sphinx = ">=6.1"
python = ">=3.9"

[feature.deps-run-oldest.dependencies]
sphinx = "6.1.*"
python = "3.9.*"

[feature.deps-test.dependencies]
pytest = ">=8"
pytest-cov = "*"
pytest-html = "*"
pytest-xdist = "*"
coverage = ">=7"
pytest-console-scripts = "*"

[feature.deps-docs.dependencies]
pydata-sphinx-theme = ">=0.15.4,<0.16.0a0"
myst-nb = "*"
sphinx-autodoc-typehints = "*"
sphinx-copybutton = "*"
sphinx-autobuild = "*"
sphinx-argparse = "*"
scour = "*"

[feature.deps-build.dependencies]
nodejs = "22.*"
yarn = "3.6.4"
datamodel-code-generator = "*"
python-build = "*"
watchfiles = "*"
ruff = "*"

[feature.deps-lint.dependencies]
ruff = "*"
mypy = "*"
taplo = "*"
actionlint-with-all = "*"
types-jinja2 = "*"
types-docutils = "*"

# tools ########################################################################
[tool.sphinx]
author = "{{ ppt.project.authors[0].name }}"
project = "{{ ppt.project.name }}"
copyright = "2024, {{ ppt.project.authors[0].name }}"
release = "{{ ppt.project.version }}"
version = "{{ ppt.project.version }}"
extensions = [
  "sphinx.ext.autodoc",
  "sphinx_autodoc_typehints",
  "sphinx.ext.intersphinx",
  "sphinx.ext.viewcode",
  "myst_nb",
  "sphinx.ext.autosectionlabel",
  "sphinx_copybutton",
  "sphinxarg.ext",
  "urljsf.sphinxext",
]
suppress_warnings = ["autosectionlabel.*"]
exclude_patterns = ["rtd.rst"]
language = "en"

## autodoc
autoclass_content = "both"
always_document_param_types = true
typehints_defaults = "comma"
typehints_use_signature_return = true
autodoc_default_options = {members = true, show-inheritance = true, undoc-members = true}
autosectionlabel_prefix_document = true

## myst
myst_heading_anchors = 3

## theme
html_theme = "pydata_sphinx_theme"
html_logo = "_static/logo.svg"
html_favicon = "_static/icon.svg"

html_theme_options.icon_links = [
  {name = "GitHub", url = "{{ ppt.project.urls.Source }}", icon = "fa-brands fa-github", type = "fontawesome"},
  {name = "PyPI", url = "{{ ppt.project.urls.PyPI }}", icon = "fa-brands fa-python", type = "fontawesome"},
]

## urljsf
urljsf.github_repo = "deathbeds/urljsf"
urljsf.css.compact_headings = true

[tool.sphinx.urljsf.css.variables]
bs-body-bg = "pst-color-background"
bs-body-color = "pst-color-text-base"
bs-card-bg = "pst-color-surface"
bs-card-cap-bg = "pst-color-danger-bg"
bs-danger-text-emphasis = "pst-color-danger-highlight"
bs-list-group-bg = "pst-color-background"
bs-list-group-color = "pst-color-text-base"
bs-secondary-color = "pst-color-text-base"
