"$id" = "https://deathbeds.github.io/_static/prjsf/example.schema.json"
"$schema" = "http://json-schema.org/draft-07/schema#"
title = "Todo"
description = "a demo of prjsf"

[properties.name]
type = "string"
description = "What is this list about?"

[properties.tasks]
type = "array"
description = "What are the tasks?"

[properties.tasks.items]
"$ref" = "#/$defs/Task"

["$defs".Task]
type = "object"

["$defs".Task.properties.complete]
type = "boolean"
description = "Is it done?"
default = false

["$defs".Task.properties.deadline]
type = "string"
description = "When does it need to be done?"
format = "date-time"

["$defs".Task.properties.task]
type = "string"
description = "What needs to be done?"
