#  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# ░░  ░░░░  ░░       ░░░  ░░░░░░░░        ░░░      ░░░        ░░░░░░░░░      ░░░
# ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒
# ▓▓  ▓▓▓▓  ▓▓       ▓▓▓  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓      ▓▓▓      ▓▓▓▓▓▓▓▓▓▓  ▓  ▓  ▓▓
# ██  ████  ██  ███  ███  ████████  ████  ████████  ██  ██████████████  ████  ██
# ███      ███  ████  ██        ███      ████      ███  ███████████████      ███
#  ▒▓████████████████████████████████████████████████████████████████████████▓▒

title = "urljsf"
description = "A schema for building forms for building URLs for building..."

"$schema" = "http://json-schema.org/draft-07/schema#"
"$id" = "https://deathbeds.github.io/urljsf/_static/schema/v0/form.schema.json"
type = "object"
required = ["url_form", "file_form"]

[properties]
url_form = {"$ref" = "#/definitions/url-form"}
file_form = {"$ref" = "#/definitions/file-form"}
theme = {"$ref" = "#/definitions/any-theme"}

[properties.iframe]
description = "isolate each form on the page in an `iframe`"
type = "boolean"

[properties.iframe_style]
description = "additional simple CSS to apply to an `iframe` element (implies `iframe`)"
type = "string"

# url form #####################################################################
[definitions.url-form]
title = "URL Form"
description = "a definition of a form to build a URL"
type = "object"
required = ["url_template"]

[definitions.url-form.properties]
url_template = {"$ref" = "#/definitions/any-url-template"}
schema = {"$ref" = "#/definitions/any-schema-location"}
ui_schema = {"$ref" = "#/definitions/any-schema-location"}
props = {"$ref" = "./props.schema.json#/definitions/Props"}

# file form ####################################################################
[definitions.file-form]
title = "File Form"
description = "a description of a form that builds a data file"
type = "object"
required = ["schema"]

[definitions.file-form.properties]
schema = {"$ref" = "#/definitions/any-schema-location"}
ui_schema = {"$ref" = "#/definitions/any-schema-location"}
form_data = {"$ref" = "#/definitions/any-schema-location"}
props = {"$ref" = "./props.schema.json#/definitions/Props"}

[definitions.file-form.properties.prune_empty]
description = "prune empty lists, object, etc."
type = "boolean"

# other ########################################################################
[definitions.any-theme]
title = "Theme"
type = "string"
default = "bootstrap"
description = """
a name of a theme supported by a compatible version of `urljsf`.

all [bootswatch] themes are available, with the vanilla [`bootstrap`][bs5] by default.

[bs5]: https://getbootstrap.com/docs/5.0
[bootswatch]: https://bootswatch.com
"""
enum = [
  "bootstrap",
  "cerulean",
  "cosmo",
  "cyborg",
  "darkly",
  "flatly",
  "journal",
  "litera",
  "lumen",
  "lux",
  "materia",
  "minty",
  "morph",
  "pulse",
  "quartz",
  "sandstone",
  "simplex",
  "sketchy",
  "slate",
  "solar",
  "spacelab",
  "superhero",
  "united",
  "vapor",
  "yeti",
  "zephyr",
]

[definitions.any-schema-location]
title = "A Schema Location"
type = "string"
format = "uri-reference"
minLength = 1
description = """
a path to a JSON schema, serialized as JSON, TOML, or (simple) YAML.
"""

[definitions.any-url-template]
title = "URL Template"
type = "string"
minLength = 1
description = """
a [nunjucks]-compatible template.

The [jinja compatibility layer][jinjacompat] is enabled, allowing for more expressive,
python-like syntax.

[nunjucks]: https://mozilla.github.io/nunjucks
[jinjacompat]: https://mozilla.github.io/nunjucks/api.html#installjinjacompat
"""
examples = [
  "https://github.com/deathbeds/urljsf/new/main?fileName=docs/_schema/v0/schema.toml",
]
